export const defaultMenu = {
  "Punjabi Main Course": [
    { name: "Paneer Kadai", desc: "Soft paneer in rich tomato-capsicum gravy with kadai masala", price: 280, popular: true, img: "/images/paneer-kadai.png" },
    { name: "Paneer Butter Masala", desc: "Creamy, buttery tomato curry with tender paneer cubes", price: 290, popular: true, img: "/images/paneer-butter-masala.png" },
    { name: "Dal Makhani", desc: "Slow-cooked black lentils in rich buttery cream sauce", price: 220, popular: false, img: "/images/dal-makhani.png" },
    { name: "Malai Kofta", desc: "Velvety paneer-potato dumplings in creamy cashew gravy", price: 270, popular: false, img: "/images/malai-kofta.png" },
    { name: "Mixed Veg Curry", desc: "Seasonal vegetables in aromatic North Indian spice blend", price: 200, popular: false, img: "/images/mixed-veg.png" },
    { name: "Chole Bhature", desc: "Spicy chickpea curry served with fluffy fried bread", price: 180, popular: true, img: "/images/chole-bhature.png" },
  ],
  "Thali": [
    { name: "Punjabi Thali", desc: "Complete meal: 2 curries, dal, rice, roti, papad, sweet, salad", price: 350, popular: true, img: "/images/punjabi-thali.png" },
    { name: "Gujarati Thali", desc: "Traditional Gujarati spread with dal, kadhi, sabzi, rotli, rice", price: 300, popular: false, img: "/images/gujarati-thali.png" },
    { name: "Special Thali", desc: "Premium thali with paneer, dal makhani, naan, dessert & more", price: 400, popular: true, img: "/images/special-thali.png" },
    { name: "Punjabi Thali (Lunch & Dinner Time)", price: 130 },
    { name: "Gujarati Thali (Only Lunch Time)", price: 110 },
  ],
  "Rice & Breads": [
    { name: "Jeera Rice", desc: "Fragrant basmati rice tempered with cumin seeds and ghee", price: 150, popular: true, img: "/images/jeera-rice.png" },
    { name: "Veg Biryani", desc: "Aromatic layered basmati with seasonal vegetables and spices", price: 220, popular: false, img: "/images/veg-biryani.png" },
    { name: "Butter Naan", desc: "Soft clay-oven baked bread brushed with melted butter", price: 60, popular: false, img: "/images/naan.png" },
    { name: "Garlic Naan", desc: "Naan topped with garlic, herbs and butter", price: 70, popular: false, img: "/images/garlic-naan.png" },
    { name: "Laccha Paratha", desc: "Flaky layered whole wheat bread, crisp and golden", price: 60, popular: false, img: "/images/laccha-paratha.png" },
  ],
  "Beverages": [
    { name: "Masala Chaas", desc: "Refreshing spiced buttermilk with cumin and fresh herbs", price: 50, popular: false, img: "/images/masala-chaas.png" },
    { name: "Fresh Lime Soda", desc: "Zesty lime with soda, sweet or salted to your taste", price: 60, popular: false, img: "/images/fresh-lime-soda.png" },
    { name: "Mango Lassi", desc: "Creamy yogurt blended with sweet Alphonso mango pulp", price: 90, popular: true, img: "/images/mango-lassi.png" },
    { name: "Masala Tea", desc: "Traditional Indian chai with aromatic spices", price: 30, popular: false, img: "/images/masala-tea.png" },
  ],
  "Paneer Ki Sabziya": [
    { name: "Paneer Kadai", price: 125 },
    { name: "Paneer Handi", price: 125 },
    { name: "Paneer Korma", price: 130 },
    { name: "Paneer Angara", price: 140 },
    { name: "Paneer Tikka Masala", price: 120 },
    { name: "Shahi Paneer", price: 140 },
    { name: "Paneer Mutter", price: 100 },
    { name: "Paneer Butter Masala (sweet)", price: 120 },
    { name: "Paneer Pasanda", price: 130 },
    { name: "Paneer Palak", price: 100 },
    { name: "Paneer Do-Pyaza", price: 120 },
    { name: "Paneer Corn Capsicum", price: 125 },
    { name: "Paneer Hyderabadi", price: 130 },
    { name: "Paneer Bhurji", price: 130 },
    { name: "Paneer Chatpata", price: 140 },
    { name: "Paneer Rajwadi", price: 140 },
    { name: "Paneer Mushroom", price: 130 },
    { name: "Chaman Methi", price: 140 },
  ],
  "Indian Veg.": [
    { name: "Veg. Kolhapuri", price: 120 },
    { name: "Veg. Makhanwala (Sweet)", price: 120 },
    { name: "Veg. Hyderabadi", price: 120 },
    { name: "Veg. Chatpata", price: 130 },
    { name: "Mix Veg.", price: 80 },
    { name: "Mushroom Masala", price: 130 },
  ],
  "Kaju & Kofta": [
    { name: "Kaju Masala", price: 135 },
    { name: "Kaju Curry (Sweet)", price: 135 },
    { name: "Khoya Kaju (Sweet)", price: 130 },
    { name: "Kaju Paneer Masala", price: 135 },
    { name: "Veg. Kofta", price: 115 },
    { name: "Malai Kofta (sweet)", price: 115 },
    { name: "Kaju Kofta", price: 125 },
    { name: "Kashmiri Kofta (sweet)", price: 115 },
    { name: "Paneer Kofta", price: 120 },
    { name: "Nargisi Kofta", price: 120 },
  ],
  "Kathiyawadi": [
    { name: "Lasaniya Bataka", price: 90 },
    { name: "Bhindi Dahi", price: 100 },
    { name: "Vagharelo Rotlo", price: 90 },
    { name: "Baingan Bharta", price: 80 },
    { name: "Kadhi Khichdi", price: 80 },
    { name: "Masala Kadhi Khichdi", price: 100 },
    { name: "Palak Khichdi", price: 90 },
    { name: "Kabuli Khichdi", price: 90 },
  ],
  "Hari Bhari Sabziya": [
    { name: "Veg. Sp. Ashirwad", price: 125 },
    { name: "Veg. Jaipuri", price: 120 },
    { name: "Navratan Korma (sweet)", price: 115 },
    { name: "Shahi Veg.", price: 120 },
    { name: "Veg. Kadai", price: 125 },
    { name: "Veg. Handi", price: 125 },
    { name: "Aloo Capsicum Masala", price: 80 },
    { name: "Aloo Jeera/Methi/Gobi/Palak/Tomato", price: 80 },
    { name: "Bhindi Do-Pyaza / Masala", price: 80 },
    { name: "Bhindi Fry", price: 80 },
    { name: "Matar Masala / Aloo Matar", price: 80 },
    { name: "Methi Masala", price: 80 },
    { name: "Aloo Matar Rasedar", price: 80 },
    { name: "Palak (Lasooni / Corn / Matar)", price: 80 },
    { name: "Gobi Masala", price: 80 },
    { name: "Chana Masala", price: 80 },
    { name: "Aloo Suki Bhaji", price: 80 },
    { name: "Sev Tomato", price: 80 },
    { name: "Matar Palak", price: 80 },
    { name: "Green Peas Curry", price: 80 },
    { name: "Masur Masala", price: 80 },
    { name: "Mung Masala", price: 80 },
    { name: "Kanda Batata", price: 80 },
  ],
  "Dal": [
    { name: "Butter Dal Fry", price: 75 },
    { name: "Dal Fry", price: 65 },
    { name: "Dal Palak", price: 75 },
    { name: "Dal Tadka", price: 75 },
  ],
  "Roti / Bread": [
    { name: "Chapati", price: 9 },
    { name: "Chapati Butter", price: 11 },
    { name: "Chapati Paratha", price: 25 },
    { name: "Tandoori Roti", price: 11 },
    { name: "Tandoori Roti Butter", price: 13 },
    { name: "Tandoori Naan", price: 30 },
    { name: "Cheese Naan", price: 50 },
    { name: "Garlic Naan", price: 50 },
    { name: "Cheese Garlic Naan", price: 60 },
    { name: "Butter Kulcha", price: 30 },
    { name: "Garlic Kulcha", price: 50 },
    { name: "Cheese Garlic Kulcha", price: 60 },
    { name: "Tandoori Paratha", price: 25 },
    { name: "Lachha Paratha", price: 30 },
    { name: "Aloo Paratha", price: 60 },
    { name: "Bajra no Rotlo", price: 25 },
  ],
  "Rice": [
    { name: "Plain Rice", price: 45 },
    { name: "Jeera Rice", price: 65 },
    { name: "Steamed Rice", price: 60 },
    { name: "Veg. Pulao", price: 85 },
    { name: "Sp. Kaju Pulao", price: 110 },
    { name: "Masoor Pulao", price: 90 },
    { name: "Veg. Biryani", price: 110 },
    { name: "Dum Biryani", price: 120 },
    { name: "Veg. Handi Biryani", price: 120 },
    { name: "Hydrabadi Biryani", price: 120 },
    { name: "Rajwadi Biryani", price: 130 },
    { name: "Dal Khichdi", price: 80 },
    { name: "Masala Rice", price: 70 },
    { name: "Kashmiri Pulao (sweet)", price: 115 },
    { name: "Peas Pulao", price: 90 },
    { name: "Paneer Pulao", price: 100 },
    { name: "Curd Rice", price: 100 },
  ],
  "South Indian": [
    { name: "Idli Sambar", price: 50 },
    { name: "Vada Sambar", price: 55 },
    { name: "Dahi Vada", price: 70 },
    { name: "Paper Dosa or Sada Dosa", price: 55 },
    { name: "Masala Dosa", price: 70 },
    { name: "Uttapam (Onion/Tomato/Masala)", price: 70 },
    { name: "Cheese Masala Dosa", price: 75 },
    { name: "Cheese Sada Dosa", price: 70 },
    { name: "Mysore Sada Dosa", price: 70 },
    { name: "Mysore Masala Dosa", price: 75 },
    { name: "Schezwan Dosa", price: 70 },
    { name: "Schezwan Masala Dosa", price: 75 },
    { name: "Dahi Idli", price: 70 },
    { name: "Idli Fry", price: 90 },
    { name: "Sev Usal", price: 50 },
  ],
  "Sp. Cheese Main Course": [
    { name: "Cheese Butter Masala", price: 140 },
    { name: "Cheese Handi", price: 135 },
    { name: "Cheese Tawa Masala", price: 140 },
    { name: "Cheese Methi Malai", price: 135 },
    { name: "Cheese Kaju Masala", price: 150 },
  ],
  "Salad / Raita": [
    { name: "Green Salad", price: 35 },
    { name: "Tomato Salad", price: 35 },
    { name: "Carrot Salad", price: 35 },
    { name: "Boondi Raita", price: 50 },
    { name: "Pineapple Raita", price: 50 },
    { name: "Veg. Raita", price: 45 },
    { name: "Curd", price: 30 },
    { name: "Butter Milk - 200ml", price: 20 },
    { name: "Masala Butter Milk - 200ml", price: 25 },
  ],
  "Papad": [
    { name: "Roasted Papad", price: 13 },
    { name: "Fry Papad", price: 15 },
    { name: "Masala Papad", price: 25 },
    { name: "Cheese Chilly Masala Papad", price: 30 },
  ],
  "Kuch Mitha Ho Jaye": [
    { name: "Gulab Jamun With Ice Cream", price: 50 },
    { name: "Royal Falooda", price: 75 },
    { name: "Lassi", price: 40 },
    { name: "Sp. Lassi", price: 65 },
    { name: "Gulab Jamun - 2 Pcs", price: 30 },
    { name: "Flavored Lassi", price: 50 },
    { name: "Sp. Flavored Lassi", price: 75 },
  ],
  "Ice Cream": [
    { name: "Vanilla", price: null },
    { name: "Mango", price: null },
    { name: "Strawberry", price: null },
    { name: "Kaju Draksh", price: null },
    { name: "Butter Scotch", price: null },
    { name: "Kesar Pista", price: null },
    { name: "Rajbhog", price: null },
    { name: "Cassata", price: null },
    { name: "Cherry Merry", price: null },
    { name: "Chocolate Chips", price: null },
    { name: "American Nut", price: null },
    { name: "Fantastic", price: null },
    { name: "Badabite", price: null },
  ],
  "Milk Shake & Juice": [
    { name: "Vanilla Milk Shake", price: 60 },
    { name: "Milk Shake (Strawberry/Butter Scotch/Chocolate/Mango)", price: 75 },
    { name: "Mava Kaju Badam Milk Shake", price: 110 },
    { name: "Kaju Anjeer Milk Shake", price: 110 },
    { name: "Kaju Badam Milk Shake", price: 110 },
  ],
  "Hot & Cold Drinks": [
    { name: "Milk", price: 40 },
    { name: "Tea", price: 20 },
    { name: "Coffee", price: 25 },
    { name: "Cold Coffee", price: 70 },
  ],
};
